### ISSUE TITLE
前端开发-完成历史事件接口的调用

### ISSUE THREAD

**Issue by mqlKKK** [buaaembeddedse/shattuckite-gui#10]
根据后端提供的api接口，完成查看历史事件的功能。
（注意分页处理展示）

**Comment by CNLHC** [comment]
@mqlKKK a9973aa3f87e77c45673e9522bf33a7361a24902 中修复了关于事件处理的Bug。接口路由不变，请测试无误后关闭该issue

**Comment by CNLHC** [comment]
已经再 3421b846009460779c3abf31055da54dba6d955c 中完成
