### ISSUE TITLE
GUI开发-为视图模型添加Typescript类型支持

### ISSUE THREAD

**Issue by CNLHC** [buaaembeddedse/shattuckite-gui#2]
请为combineReducer函数创建的store添加强类型支持。具体可以通过以下方式实现

1. 对于每一个Container组件的reducer，请为它们建立自己的类型。参考易迈科技无人购物前端某个页面的[reducer.ts](https://github.com/CNLHC/SSB-Web/blob/master/ssb-front/src/containers/PageSettle/reducer.ts)。最好将该类型命名为`IPage<page_name>Reducer`。

2. 提供一个根类型，用于描述视图模型状态树的类型。参考 [TypeRoot.ts](https://github.com/CNLHC/SSB-Web/blob/master/ssb-front/src/Typings/TypeRoot.ts).

**Comment by mqlKKK** [comment]
已经完成

**Comment by CNLHC** [comment]
> 已经完成

@mqlKKK 请在issue中指出commit记录，然后关闭这个issue。

**Comment by mqlKKK** [comment]
[https://github.com/buaaembeddedse/shattuckite-gui/commit/7419faefae9f14ca2499dde6d47e2f70a325ed33](url)
