### ISSUE TITLE
关于系统前后端交互的讨论

### ISSUE THREAD

**Issue by mqlKKK** [buaaembeddedse/shattuckite-gui#8]

**Comment by mqlKKK** [comment]
关于事件的逻辑：将事件通过status属性（“unhandled”和“handled”）分为“当前事件”和“历史事件”，“当前事件”处理后改变status成为“历史事件”，并且不可逆，如何？

**Comment by mqlKKK** [comment]
从服务器获取的数据存在八小时时差，是否设置存在疏忽？

**Comment by CNLHC** [comment]
> 关于事件的逻辑：将事件通过status属性（“unhandled”和“handled”）分为“当前事件”和“历史事件”，“当前事件”处理后改变status成为“历史事件”，并且不可逆，如何？ @CNLHC

可以，符合需求文档描述

**Comment by CNLHC** [comment]
> 从服务器获取的数据存在八小时时差，是否设置存在疏忽？

是的，后端忘记设置时区了。已经在 ff82441d61f9f48b35e156e11041ce3ed6f685ac 中修复
